/**
 * @description       :
 * @author            : mateo navarrete
 * @group             : BizOps
 * @last modified on  : 12-16-2020
 * @last modified by  : mateo navarrete
 * Modifications Log
 * Ver   Date         Author            Modification
 * 1.0   12-16-2020   mateo navarrete   Initial Version
 **/
@isTest
public class CustomFileUploaderTest {
  @isTest
  static void getTest() {
    //
  }
}
