/**
 * @description       : Custom exception class for MockDataAPIController.cls
 * @author            : mateo navarrete
 * @group             : BizOps
 * @last modified on  : 12-02-2020
 * @last modified by  : mateo navarrete
 * Modifications Log
 * Ver   Date         Author                               Modification
 * 1.0   11-19-2020   mateo navarrete   Initial Version
 **/
public class MockDataException extends Exception {
}